refactor(hammer): made some tweaks
protokol/examples pull request #53
Opened 2021-02-11 07:41 UTC by KovacZan

## Summary
Added new asset types and made some small changes.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

2021-02-11 09:21 UTC, amacar requested changes

2021-02-11 09:21 UTC, amacar commented on packages/hammer/src/setup.ts
>  	Managers.configManager.setConfig({
You can use the whole crypto config that you get from the node.
```suggestion
	Managers.configManager.setConfig(configs);
```

2021-02-11 09:21 UTC, amacar commented on packages/hammer/src/setup.ts
> +	Managers.configManager.setHeight(2);
Use correct height from node.
```suggestion
        const { body: { data: { block : { height } } } }= await client.get("blockchain");
	Managers.configManager.setHeight(height );
```

2021-02-11 09:21 UTC, amacar commented on packages/hammer/src/scripts/nonces.ts
> +}
Reuse `getNonce` function

```suggestion
async function getNextNonce(client: ProtokolConnection, passphrase: string): Promise<Utils.BigNumber> {
	const nonce = await getNonce(client, passphrase);
	return nonce.plus(1);
}
```

2021-02-11 09:21 UTC, amacar commented on packages/hammer/src/scripts/ShareCoinsScript.ts
> +		let nonce = Utils.BigNumber.make(wallet.body.data.nonce);
Use `getNonce` or `getNextNonce` for initial nonce if nothing else from the wallet is used.

2021-02-11 09:21 UTC, amacar commented on packages/hammer/src/scripts/FillScript.ts
> +				let nonce = await this.getNonce(pass!);
Use `getNextNonce` from` scripts/nonce`

2021-02-11 09:21 UTC, amacar commented on packages/hammer/src/scripts/FillScript.ts
> +		}
I would prefer the previous implementation, but your choice. :)

2021-02-11 09:21 UTC, amacar commented on packages/hammer/src/script.ts
> +	await delay(configurations.delay);
You can destructure.
```
const { passphrasesFile, delay } = configurations;

// and later
await shareCoins.splitCoins(50000, passphrasesFile.secrets);
await delay(delay);
```

2021-02-11 12:04 UTC, KovacZan commented on packages/hammer/src/setup.ts
>  	Managers.configManager.setConfig({
You can't, because genesis block parameters don't fit in.
I could ts-ignore it or something but anyways genesis block doesn't impact crypto create transactions.

2021-02-11 12:09 UTC, KovacZan commented on packages/hammer/src/scripts/FillScript.ts
> +		}
yeah, you are right.
I might miss that while merging.

2021-02-12 11:10 UTC, amacar submitted a review, later dismissed

2021-02-12 11:11 UTC, amacar commented
Please fix conflicts and we are ready to merge.

2021-02-12 15:45 UTC, amacar approved these changes

2021-02-12 15:46 UTC, merged